name: my_project
version: '1.0'
config-version: 2

profile: my_project  # This must match your profiles.yml

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  my_project:
    staging:
      +materialized: view
    dimensions:
      +materialized: view
    facts:
      +materialized: incremental
