version: 2

models:

  - name: dim_clients
    description: "Dimension table for clients"
    columns:
      - name: sev_client_id
        tests:
          - not_null
      - name: signed_up_at_utc  
        tests:
          - not null
      - name: registration_finished_at_utc 
        tests:
          - not null
      - name: has_active_contract_current 
        tests:
          - not null
      - name: _valid_from_utc 
        tests:
          - not null


  - name: dim_dates
    description: "Dimension table for dates"
    columns:
      - name: date_day
        tests:
          - not_null
          
