version: 2

models:
  - name: stg_intercom_conversation
    description: "Staging table for intercom conversations"
    columns:
      - name: conversation_id
        description: "conversation part ID"
        tests:
          - not_null
      - name: author_contact_id  
        tests:
          - not null
      - name: sev_client_id 
        tests:
          - relationships:
              to: ref('dim_client')
              field: conversation_id
      - name: created_at_utc 
        tests:
          - not null
      - name: updated_at_utc 
        tests:
          - not null
      - name: first_closed_at_utc 
        tests:
          - not null
      - name: last_closed_at_utc 
        tests:
          - not null


  - name: stg_intercom_conversation_parts
    description: "Staging table for intercom conversation parts"
    columns:
      - name: conversation_part_id
        description: "conversation part ID"
        tests:
          - not_null
      - name: conversation_id  
        tests:
          - relationships:
              to: ref('stg_intercom_conversations')
              field: conversation_id
      - name: created_at_utc 
        tests:
          - not null
      - name: updated_at_utc 
        tests:
          - not null
      - name: part_type 
        tests:
          - not null
      - name: is_first_agent_reply 
        tests:
          - not null

